// This file was generated by a tool. Modifying it will produce unexpected behavior

export interface IExportStyles {
  'adminCard': string;

  'adminDetails': string;

  'adminGrid': string;

  'adminHeader': string;

  'badgeContribute': string;

  'badgeEdit': string;

  'badgeFullControl': string;

  'badgeInherited': string;

  'badgeRead': string;

  'badgeUnique': string;

  'checkAccessContainer': string;

  'content': string;

  'deepScanModal': string;

  'exportBtn': string;

  'govBtn': string;

  'govIcon': string;

  'govList': string;

  'govStat': string;

  'govStatAlert': string;

  'govStatInfo': string;

  'govStatWarning': string;

  'govTitle': string;

  'governanceCard': string;

  'governanceGrid': string;

  'header': string;

  'headerStatBtn': string;

  'headerStats': string;

  'inheritedInfo': string;

  'layoutContainer': string;

  'layoutContainerTop': string;

  'listCard': string;

  'listCardHeader': string;

  'listIcon': string;

  'listTitle': string;

  'listUrl': string;

  'loadingState': string;

  'loadingText': string;

  'mainCanvas': string;

  'ms-Dialog-subText': string;

  'ms-Dialog-title': string;

  'navigation': string;

  'navigationTop': string;

  'permissionBadge': string;

  'permissionTable': string;

  'permissionViewer': string;

  'searchBox': string;

  'statCard': string;

  'statIcon': string;

  'statLabel': string;

  'statNumber': string;

  'statsContainer': string;

  'tabsContainer': string;

  'toolbar': string;

  'userCell': string;

  'userEmail': string;

  'userInfo': string;

  'userName': string;

  'userResultItem': string;

  'webpartContainer': string;

}

declare const strings: IExportStyles;

export default strings;